# Travis-CI configuration

sudo: true
services:
    - docker

language: cpp

matrix:
  include:
    - os: linux
      env: BASE_IMAGE=baagaard/codecov-testenv-debian-stable-gcc8
    - os: linux
      env: BASE_IMAGE=baagaard/codecov-testenv-debian-testing-gcc9


addons:
  apt:
    packages:
      - docker-ce


# Limit number of commits in cloning (but keep enough so that 'git describe' works)
git:
  depth: 100


install:
  - docker build -t codecov-testenv --build-arg BASE_IMAGE=$BASE_IMAGE --target src -f docker/codecov-testenv .


script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env codecov-testenv /bin/bash -c "make && make check VERBOSE=1 && make coverage-libsrc"
